dist: bionic
language: julia
os:
  - linux
env:
  - JAVA_HOME=/usr/local/lib/jvm/openjdk8
  - JAVA_HOME=/usr/local/lib/jvm/openjdk11
julia:
  - 1.0
  - 1.4
  - nightly
notifications:
  email: false
matrix:
  allow_failures:
    - julia: nightly

branches:
  only:
    - master
    - /release-.*/

before_install:
  - sudo apt-get install -y maven

# uncomment the following lines to override the default test script
#script:
# - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
# - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("Spark"); Pkg.test("Spark"; coverage=true)'
